from check_types import ALLOWED_TYPES_BY_CATEGORY
from utils import (
    CATEGORY_LABELS,
    EVENT_CATEGORIES,
    EVENT_TYPE,
    ROOT,
    SCHEMA_FILE,
    load_json,
    log,
)

SCHEMA_DOC = ROOT / "docs" / "SCHEMA.md"

FIELD_DOCS = {
    "id": ("Unique stable identifier, lowercase, hyphens", '"uoftctf"'),
    "name": ("Display name of the resource", '"UofTCTF"'),
    "url": ("Full URL including https://", '"https://ctf.uoftctf.org"'),
    "description": (
        "One sentence, ends with period",
        '"Beginner-friendly CTF platform."',
    ),
    "category": ("Must match folder name", '"ctfs"'),
    "date_added": ("ISO date the resource was added", '"2026-06-15"'),
    "last_verified": ("ISO date the URL was last confirmed active", '"2026-06-15"'),
    "type": ("Resource type from the allowed list for the category", '"course"'),
    "month": ("Month name for recurring or seasonal resources", '"March"'),
    "location": ("Exact location or `Online` when useful", '"Montreal, Quebec"'),
}


def markdown_table(headers: list[str], rows: list[list[str]]) -> list[str]:
    widths = [
        max(len(headers[column]), *(len(row[column]) for row in rows))
        if rows
        else len(headers[column])
        for column in range(len(headers))
    ]
    header = "| " + " | ".join(h.ljust(w) for h, w in zip(headers, widths)) + " |"
    divider = "| " + " | ".join("-" * w for w in widths) + " |"
    body = [
        "| " + " | ".join(cell.ljust(w) for cell, w in zip(row, widths)) + " |"
        for row in rows
    ]
    return [header, divider, *body]


def field_rows(schema: dict, fields: list[str]) -> list[str]:
    rows = []
    for field in fields:
        json_type = schema["properties"][field]["type"]
        description, example = FIELD_DOCS[field]
        rows.append([f"`{field}`", json_type, description, f"`{example}`"])
    return markdown_table(["Field", "Type", "Description", "Example"], rows)


def generate_schema_docs() -> None:
    schema = load_json(SCHEMA_FILE)
    properties = schema["properties"]

    undocumented = sorted(set(properties) - set(FIELD_DOCS))
    unknown = sorted(set(FIELD_DOCS) - set(properties))
    if undocumented or unknown:
        problems = []
        if undocumented:
            problems.append(f"missing from FIELD_DOCS: {', '.join(undocumented)}")
        if unknown:
            problems.append(f"not in the schema: {', '.join(unknown)}")
        raise SystemExit(
            "❌ generate_schema_docs.py FIELD_DOCS is out of sync -- "
            + "; ".join(problems)
        )

    required = [field for field in properties if field in schema["required"]]
    optional = [field for field in properties if field not in schema["required"]]

    lines = [
        "<!-- Generated by scripts/generate_schema_docs.py. Do not edit by hand. -->",
        "",
        "# Schema Reference",
        "",
        "Every resource in `data/` follows the schema defined in "
        "`schema/resource.schema.json`.",
        "",
        "## Fields",
        "",
        "### Required",
        "",
        *field_rows(schema, required),
        "",
        "### Optional",
        "",
        *field_rows(schema, optional),
        "",
        "## Allowed `type` values",
        "",
        "`type` is optional for every category, but when it is set it must come from "
        "the list below. Anything else fails validation in `scripts/check_types.py`.",
        "",
    ]

    type_rows = []
    for category in CATEGORY_LABELS:
        allowed = ALLOWED_TYPES_BY_CATEGORY.get(category, set())
        values = ", ".join(f"`{value}`" for value in sorted(allowed)) or "--"
        type_rows.append([f"`{category}`", values])
    lines += markdown_table(["Category", "Allowed `type` values"], type_rows)

    experience = ", ".join(f"`{category}`" for category in sorted(EVENT_CATEGORIES))
    lines += [
        "",
        f"`{EVENT_TYPE}` is reserved for the Experience collection ({experience}) and "
        "is rejected in any other category. Those categories accept no other type.",
        "",
        "## Example Entry",
        "",
        "```json",
        "{",
        '  "id": "leetcode",',
        '  "name": "LeetCode",',
        '  "url": "https://leetcode.com",',
        '  "description": "Coding interview platform with algorithms, data '
        'structures, SQL, and system design problems.",',
        '  "category": "interview-prep",',
        '  "type": "platform",',
        '  "date_added": "2026-06-15",',
        '  "last_verified": "2026-06-15"',
        "}",
        "```",
        "",
    ]

    SCHEMA_DOC.write_text("\n".join(lines), encoding="utf-8")
    log(f"✅ Generated SCHEMA.md ({len(properties)} fields)")


if __name__ == "__main__":
    generate_schema_docs()
