from collections import defaultdict
from datetime import date

from utils import (
    CATEGORY_GROUPS,
    CATEGORY_LABELS,
    GENERATED_DIR,
    ROOT,
    load_all_resources,
    log,
    save_json,
)

CATEGORY_ICONS = {
    "learning-resources": "📚",
    "communities": "💬",
    "clubs": "🎓",
    "volunteer": "❤️",
    "ctfs": "🔐",
    "competitions": "🏆",
    "hackathons": "💻",
    "game-jams": "🎮",
    "projects": "🧩",
    "repositories": "📦",
    "open-source-help": "🤝",
    "research": "🔬",
    "conferences": "📢",
    "fellowships": "🌟",
    "online-events": "🌐",
    "career-fairs": "💼",
    "scholarships": "💰",
    "startup-programs": "🚀",
    "freelance": "💸",
    "certifications": "🏅",
    "free-benefits": "🎁",
}

GROUP_ICONS = {
    "Learning & Development": "📚",
    "Experience & Involvement": "🏆",
    "Building & Open Source": "🧩",
    "Academic & Professional": "🔬",
    "Networking & Opportunities": "💼",
    "Credentials & Perks": "🏅",
}


def category_anchor(category: str) -> str:
    return category


def category_count(by_category: dict[str, list[dict]], category: str) -> int:
    return len(by_category.get(category, []))


def shield(label: str, message: str, color: str) -> str:
    return f"![{label}](https://img.shields.io/badge/{label}-{message}-{color})"


def generate_readme():
    resources = load_all_resources()
    by_category = defaultdict(list)
    for resource in resources:
        by_category[resource["category"]].append(resource)

    total = len(resources)
    today = str(date.today())
    lines = []
    lines.append("<!-- This README is generated by scripts/generate_readme.py. -->\n\n")
    lines.append('<div align="center">\n\n')
    lines.append("# CS Resource Hub\n\n")
    lines.append(
        "**A curated, automated dataset of North American Computer Science "
        "student resources.**\n\n"
    )
    lines.append(
        "Built on structured JSON with a Python CI pipeline for schema "
        "validation, quality checks, link monitoring, and multi-format exports.\n\n"
    )
    badges = [
        shield("resources", str(total), "2563eb"),
        shield("updated", today, "7c3aed"),
        shield("code_license", "MIT", "16a34a"),
        shield("data_license", "CC_BY_4.0", "0f766e"),
        shield("contributions", "welcome", "f59e0b"),
    ]
    lines.append(" ".join(badges))
    lines.append("\n\n</div>\n\n")
    lines.append("\n---\n\n")
    lines.append("## Overview\n\n")
    lines.append(
        "CS Resource Hub organizes North American student-friendly resources into "
        "a clean dataset that can power this README, future websites, search "
        "tools, dashboards, or other apps.\n\n"
    )
    lines.append("| Dataset | Automation | Exports |\n")
    lines.append("| --- | --- | --- |\n")
    lines.append(
        f"| {len(CATEGORY_LABELS)} categories · {total} resources | "
        "Schema validation · quality checks · link monitoring | "
        "README · CSV · site-ready JSON |\n"
    )
    lines.append("\n| Focus area | Categories | Resources |\n")
    lines.append("| --- | ---: | ---: |\n")
    for group, categories in CATEGORY_GROUPS.items():
        group_total = sum(
            category_count(by_category, category) for category in categories
        )
        lines.append(
            f"| {GROUP_ICONS[group]} {group} | {len(categories)} | {group_total} |\n"
        )

    lines.append("\n## Browse\n\n")
    lines.append("| Area | Categories |\n")
    lines.append("| --- | --- |\n")
    for group, categories in CATEGORY_GROUPS.items():
        category_links = []
        for category in categories:
            icon = CATEGORY_ICONS[category]
            label = CATEGORY_LABELS[category]
            count = category_count(by_category, category)
            category_links.append(
                f"{icon} [{label}](#{category_anchor(category)}) "
                f"<sub>{count}</sub>"
            )
        joined_links = "<br>".join(category_links)
        lines.append(f"| {GROUP_ICONS[group]} {group} | {joined_links} |\n")

    lines.append("\n---\n")

    for category, label in CATEGORY_LABELS.items():
        cat_resources = sorted(
            by_category.get(category, []), key=lambda x: -x.get("quality", 0)
        )
        lines.append(f'\n<a id="{category_anchor(category)}"></a>\n\n')
        lines.append(f"## {CATEGORY_ICONS[category]} {label}\n\n")
        lines.append(f"**{len(cat_resources)} resources** · `{category}`\n\n")
        if cat_resources:
            lines.append("| Resource | Description | Cost | Region | Tags |\n")
            lines.append("| --- | --- | --- | --- | --- |\n")
            for r in cat_resources:
                name = f"[{r['name']}]({r['url']})"
                desc = r.get("description", "")
                cost = r.get("cost", "")
                region = ", ".join(r.get("region", []))
                tags = ", ".join(r.get("tags", []))
                lines.append(f"| {name} | {desc} | {cost} | {region} | {tags} |\n")
        else:
            lines.append("> No resources yet. Contributions are welcome.\n")

    lines.append("\n---\n\n")
    lines.append("## Contributing\n\n")
    lines.append("Contributions keep this dataset useful and current.\n\n")
    lines.append("1. Read [CONTRIBUTING.md](./CONTRIBUTING.md).\n")
    lines.append("2. Pick the correct category in `data/`.\n")
    lines.append("3. Add one resource using the JSON schema.\n")
    lines.append("4. Run `make validate` and `make check-duplicates`.\n")
    lines.append("5. Open a pull request with a clear description.\n")
    lines.append("\n## License\n\n")
    lines.append("- Code and scripts: [MIT](./LICENSE)\n")
    lines.append("- Dataset/content: [CC BY 4.0](./LICENSE-CC-BY)\n")
    lines.append("\n---\n\n")
    lines.append('<div align="center">\n\n')
    lines.append(
        "Built for North American Computer Science students who want one reliable "
        "place to discover what to learn, "
    )
    lines.append("join, build, attend, and apply for.\n\n")
    lines.append("</div>\n")

    readme = "".join(lines)
    readme_path = ROOT / "README.md"
    with open(readme_path, "w", encoding="utf-8") as f:
        f.write(readme)

    save_json(
        GENERATED_DIR / "README_DATA.json",
        {
            "generated": today,
            "total": total,
            "by_category": {k: len(v) for k, v in by_category.items()},
        },
    )

    log(f"✅ Generated README.md ({total} resources)")

if __name__ == "__main__":
    generate_readme()
