from collections import defaultdict
from urllib.parse import quote_plus

from utils import (
    CATEGORY_GROUPS,
    CATEGORY_LABELS,
    ROOT,
    dataset_updated_date,
    load_all_resources,
    log,
)

GROUP_ICONS = {
    "Learning & Development": "📚",
    "Experience": "🏆",
    "Building & Open Source": "🧩",
    "Careers & Perks": "💼",
}
TECH_ICONS = [
    (
        "Python",
        "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/python/python-original.svg",
    ),
    (
        "JSON Schema",
        "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/json/json-original.svg",
    ),
    (
        "GitHub Actions",
        "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/githubactions/githubactions-original.svg",
    ),
]

MONTH_ORDER = {
    "January": 1,
    "February": 2,
    "March": 3,
    "April": 4,
    "May": 5,
    "June": 6,
    "July": 7,
    "August": 8,
    "September": 9,
    "October": 10,
    "November": 11,
    "December": 12,
}


def category_anchor(category: str) -> str:
    return category


def category_count(by_category: dict[str, list[dict]], category: str) -> int:
    return len(by_category.get(category, []))


def shield(label: str, message: str, color: str) -> str:
    return (
        "!["
        f"{label}"
        "](https://img.shields.io/static/v1?"
        f"label={quote_plus(label)}&message={quote_plus(message)}&color={color})"
    )


def workflow_badge(label: str, workflow: str) -> str:
    encoded_label = quote_plus(label)
    badge = (
        f"https://img.shields.io/github/actions/workflow/status/"
        f"NicholasXydis/CSResourceHub/{workflow}?"
        f"branch=main&label={encoded_label}&color=16a34a"
    )
    target = (
        f"https://github.com/NicholasXydis/CSResourceHub/actions/workflows/"
        f"{workflow}"
    )
    return f"[![{label}]({badge})]({target})"


def count_badge(count: int) -> str:
    return f"({count})"


def typing_svg(lines: list[str]) -> str:
    encoded_lines = ";".join(quote_plus(line) for line in lines)
    return (
        "[![Typing SVG](https://readme-typing-svg.demolab.com?"
        "font=Fira+Code&pause=1000&color=4A90D9&center=true&"
        f"vCenter=true&width=760&lines={encoded_lines})]"
        "(https://git.io/typing-svg)"
    )


def tech_icon(name: str, src: str) -> str:
    return f'<img src="{src}" alt="{name}" width="52" height="52">'


def resource_sort_key(resource: dict):
    resource_type = resource.get("type")
    month = resource.get("month")
    month_order = MONTH_ORDER.get(month, len(MONTH_ORDER) + 1)
    name = resource["name"].lower()
    if resource_type:
        return (0, resource_type, month_order, name)
    return (1, month_order, name)


def format_type(resource_type: str) -> str:
    label = resource_type.replace("-", " ").replace("_", " ").title()
    return label.replace("Api", "API")


def generate_readme():
    resources = load_all_resources()
    by_category = defaultdict(list)
    for resource in resources:
        by_category[resource["category"]].append(resource)

    total = len(resources)
    updated = dataset_updated_date(resources)
    lines = []
    lines.append("<!-- This README is generated by scripts/generate_readme.py. -->\n\n")
    lines.append('<div align="center">\n\n')
    lines.append("# CS Resource Hub\n\n")
    lines.append(
        typing_svg(
            [
                "Curated Canadian CS Opportunities",
                "Learning | Hackathons | Careers | Developer Perks",
                "Validated JSON Dataset With Automated Checks",
                "Generated README | CSV | Site-Ready JSON",
            ]
        )
    )
    lines.append("\n\n")
    lines.append(
        "**A curated, automated dataset of Canadian Computer Science "
        "student resources.**\n\n"
    )
    lines.append("<br>\n\n<br>\n\n")
    lines.append('<p align="center">\n')
    lines.append(
        "  "
        + "\n  &nbsp;&nbsp;\n  ".join(
            tech_icon(name, src) for name, src in TECH_ICONS
        )
        + "\n"
    )
    lines.append("</p>\n\n")
    lines.append('<p align="center">\n')
    lines.append(
        f"  <strong>{len(CATEGORY_LABELS)} CS Opportunity Categories</strong> "
        "&nbsp;|&nbsp; <strong>Automated Validation</strong> &nbsp;|&nbsp; "
        "<strong>Multi-Format Exports</strong>\n"
    )
    lines.append("</p>\n\n")
    badges = [
        shield("resources", str(total), "2563eb"),
        workflow_badge("CI", "validate.yml"),
        shield("contributions", "welcome", "f59e0b"),
        shield("updated", updated, "7c3aed"),
    ]
    lines.append(" ".join(badges))
    lines.append("\n\n</div>\n\n")
    lines.append("<br>\n\n")
    lines.append('<div align="center">\n')
    lines.append(
        '  <img src="docs/data-pipeline.svg" '
        'alt="CS Resource Hub data pipeline" width="100%">\n'
    )
    lines.append("</div>\n\n")
    lines.append("<br>\n\n")
    lines.append("## Browse\n\n")
    lines.append("Browse resources by area and category.\n\n")
    lines.append("| Area | Categories |\n")
    lines.append("| --- | --- |\n")
    for group, categories in CATEGORY_GROUPS.items():
        category_links = []
        for category in categories:
            label = CATEGORY_LABELS[category]
            count = category_count(by_category, category)
            category_links.append(
                f"[{label}](#{category_anchor(category)}) {count_badge(count)}"
            )
        joined_links = "<br>".join(category_links)
        lines.append(f"| {GROUP_ICONS[group]} {group} | {joined_links} |\n")

    lines.append("\n")

    for group, categories in CATEGORY_GROUPS.items():
        lines.append(f"\n## {GROUP_ICONS[group]} {group}\n\n")
        for category in categories:
            label = CATEGORY_LABELS[category]
            cat_resources = sorted(
                by_category.get(category, []), key=resource_sort_key
            )
            lines.append(f'<a id="{category_anchor(category)}"></a>\n\n')
            lines.append(f"### {label}\n\n")
            lines.append(f"**{len(cat_resources)} resources** · `{category}`\n\n")
            if cat_resources:
                has_month = any(r.get("month") for r in cat_resources)
                has_location = any(r.get("location") for r in cat_resources)
                has_type = any(r.get("type") for r in cat_resources)
                if has_type or has_month or has_location:
                    headers = ["Resource", "Description"]
                    if has_type:
                        headers.append("Type")
                    if has_month:
                        headers.append("Month")
                    if has_location:
                        headers.append("Location")
                    lines.append(f"| {' | '.join(headers)} |\n")
                    lines.append(f"| {' | '.join('---' for _ in headers)} |\n")
                    for r in cat_resources:
                        name = f"[{r['name']}]({r['url']})"
                        row = [name, r.get("description", "")]
                        if has_type:
                            row.append(format_type(r.get("type", "")) or "Resource")
                        if has_month:
                            row.append(r.get("month") or "Ongoing")
                        if has_location:
                            row.append(r.get("location") or "TBD")
                        lines.append(f"| {' | '.join(row)} |\n")
                else:
                    lines.append("| Resource | Description |\n")
                    lines.append("| --- | --- |\n")
                    for r in cat_resources:
                        name = f"[{r['name']}]({r['url']})"
                        desc = r.get("description", "")
                        lines.append(f"| {name} | {desc} |\n")
            else:
                lines.append("> No resources yet. Contributions are welcome.\n")
            lines.append("\n")

    lines.append("\n")
    lines.append("## Contributing\n\n")
    lines.append("Contributions keep this dataset useful and current.\n\n")
    lines.append(
        "1. Read [CONTRIBUTING.md](./CONTRIBUTING.md) and "
        "[ADDING_RESOURCES.md](./docs/ADDING_RESOURCES.md).\n"
    )
    lines.append("2. Run `make add` or pick the correct JSON file in `data/`.\n")
    lines.append(
        "3. Add one resource using [SCHEMA.md](./docs/SCHEMA.md) and "
        "[STYLE_GUIDE.md](./docs/STYLE_GUIDE.md).\n"
    )
    lines.append("4. Run `make validate`.\n")
    lines.append("5. Open a pull request with a clear description.\n")
    lines.append("\n## License\n\n")
    lines.append("- Code and scripts: [MIT](./LICENSE)\n")
    lines.append("- Dataset/content: [CC BY 4.0](./LICENSE-CC-BY)\n")
    lines.append("\n")
    lines.append('<div align="center">\n\n')
    lines.append(
        "Built for Canadian Computer Science students who want one reliable "
        "place to discover what to learn, "
    )
    lines.append("join, build, attend, and apply for.\n\n")
    lines.append("</div>\n")

    readme = "".join(lines)
    readme_path = ROOT / "README.md"
    with open(readme_path, "w", encoding="utf-8") as f:
        f.write(readme)


    log(f"✅ Generated README.md ({total} resources)")

if __name__ == "__main__":
    generate_readme()
