from collections import defaultdict
from datetime import date
from urllib.parse import quote_plus

from utils import (
    CATEGORY_GROUPS,
    CATEGORY_LABELS,
    GENERATED_DIR,
    ROOT,
    load_all_resources,
    log,
    save_json,
)

CATEGORY_ICONS = {
    "learning-resources": "📚",
    "communities": "💬",
    "clubs": "🎓",
    "volunteer": "❤️",
    "ctfs": "🔐",
    "competitions": "🏆",
    "hackathons": "💻",
    "game-jams": "🎮",
    "projects": "🧩",
    "repositories": "📦",
    "open-source-help": "🤝",
    "research": "🔬",
    "conferences": "📢",
    "fellowships": "🌟",
    "online-events": "🌐",
    "career-fairs": "💼",
    "scholarships": "💰",
    "startup-programs": "🚀",
    "freelance": "💸",
    "certifications": "🏅",
    "free-benefits": "🎁",
}

GROUP_ICONS = {
    "Learning & Development": "📚",
    "Experience & Involvement": "🏆",
    "Building & Open Source": "🧩",
    "Academic & Professional": "🔬",
    "Networking & Opportunities": "💼",
    "Credentials & Perks": "🏅",
}

TECH_ICONS = [
    (
        "Python",
        "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/python/python-original.svg",
    ),
    (
        "JSON",
        "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/json/json-original.svg",
    ),
    (
        "GitHub Actions",
        "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/githubactions/githubactions-original.svg",
    ),
    (
        "Markdown",
        "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/markdown/markdown-original.svg",
    ),
]


def category_anchor(category: str) -> str:
    return category


def category_count(by_category: dict[str, list[dict]], category: str) -> int:
    return len(by_category.get(category, []))


def shield(label: str, message: str, color: str) -> str:
    return (
        "!["
        f"{label}"
        "](https://img.shields.io/static/v1?"
        f"label={quote_plus(label)}&message={quote_plus(message)}&color={color})"
    )


def count_badge(count: int) -> str:
    return f"({count})"


def typing_svg(lines: list[str]) -> str:
    encoded_lines = ";".join(quote_plus(line) for line in lines)
    return (
        "[![Typing SVG](https://readme-typing-svg.demolab.com?"
        "font=Fira+Code&pause=1000&color=4A90D9&center=true&"
        f"vCenter=true&width=760&lines={encoded_lines})]"
        "(https://git.io/typing-svg)"
    )


def tech_icon(name: str, src: str) -> str:
    return f'<img src="{src}" alt="{name}" width="52" height="52">'


def generate_readme():
    resources = load_all_resources()
    by_category = defaultdict(list)
    for resource in resources:
        by_category[resource["category"]].append(resource)

    total = len(resources)
    today = str(date.today())
    lines = []
    lines.append("<!-- This README is generated by scripts/generate_readme.py. -->\n\n")
    lines.append('<div align="center">\n\n')
    lines.append("# CS Resource Hub\n\n")
    lines.append(
        typing_svg(
            [
                "Curated CS Opportunities Across North America",
                "Scholarships | Hackathons | Research | Fellowships",
                "Validated JSON Dataset With Automated Quality Gates",
                "Generated README | CSV | Site-Ready JSON",
            ]
        )
    )
    lines.append("\n\n")
    lines.append(
        "**A curated, automated dataset of North American Computer Science "
        "student resources.**\n\n"
    )
    lines.append("<br>\n\n<br>\n\n")
    lines.append('<p align="center">\n')
    lines.append(
        "  "
        + "\n  &nbsp;&nbsp;\n  ".join(
            tech_icon(name, src) for name, src in TECH_ICONS
        )
        + "\n"
    )
    lines.append("</p>\n\n")
    lines.append('<p align="center">\n')
    lines.append(
        f"  <strong>{len(CATEGORY_LABELS)} CS Opportunity Categories</strong> "
        "&nbsp;|&nbsp; <strong>Automated Quality Gates</strong> &nbsp;|&nbsp; "
        "<strong>Multi-Format Exports</strong>\n"
    )
    lines.append("</p>\n\n")
    badges = [
        shield("resources", str(total), "2563eb"),
        shield("quality gates", "passing", "16a34a"),
        shield("contributions", "welcome", "f59e0b"),
        shield("updated", today, "7c3aed"),
    ]
    lines.append(" ".join(badges))
    lines.append("\n\n</div>\n\n")
    lines.append("<br>\n\n")
    lines.append('<div align="center">\n')
    lines.append(
        '  <img src="docs/data-pipeline.svg" '
        'alt="CS Resource Hub data pipeline" width="85%">\n'
    )
    lines.append("</div>\n\n")
    lines.append("<br>\n\n")
    lines.append("## Browse\n\n")
    lines.append("Browse resources by focus area and category.\n\n")
    lines.append("| Area | Categories |\n")
    lines.append("| --- | --- |\n")
    for group, categories in CATEGORY_GROUPS.items():
        category_links = []
        for category in categories:
            icon = CATEGORY_ICONS[category]
            label = CATEGORY_LABELS[category]
            count = category_count(by_category, category)
            category_links.append(
                f"{icon} [{label}](#{category_anchor(category)}) "
                f"{count_badge(count)}"
            )
        joined_links = "<br>".join(category_links)
        lines.append(f"| {GROUP_ICONS[group]} {group} | {joined_links} |\n")

    lines.append("\n")

    for category, label in CATEGORY_LABELS.items():
        cat_resources = sorted(
            by_category.get(category, []), key=lambda x: -x.get("quality", 0)
        )
        lines.append(f'\n<a id="{category_anchor(category)}"></a>\n\n')
        lines.append(f"## {CATEGORY_ICONS[category]} {label}\n\n")
        lines.append(f"**{len(cat_resources)} resources** · `{category}`\n\n")
        if cat_resources:
            lines.append("| Resource | Description | Cost | Region | Tags |\n")
            lines.append("| --- | --- | --- | --- | --- |\n")
            for r in cat_resources:
                name = f"[{r['name']}]({r['url']})"
                desc = r.get("description", "")
                cost = r.get("cost", "")
                region = ", ".join(r.get("region", []))
                tags = ", ".join(r.get("tags", []))
                lines.append(f"| {name} | {desc} | {cost} | {region} | {tags} |\n")
        else:
            lines.append("> No resources yet. Contributions are welcome.\n")

    lines.append("\n")
    lines.append("## Contributing\n\n")
    lines.append("Contributions keep this dataset useful and current.\n\n")
    lines.append(
        "1. Read [CONTRIBUTING.md](./CONTRIBUTING.md) and "
        "[ADDING_RESOURCES.md](./docs/ADDING_RESOURCES.md).\n"
    )
    lines.append("2. Run `make add` or pick the correct JSON file in `data/`.\n")
    lines.append(
        "3. Add one resource using [SCHEMA.md](./docs/SCHEMA.md) and "
        "[STYLE_GUIDE.md](./docs/STYLE_GUIDE.md).\n"
    )
    lines.append("4. Run `make validate`.\n")
    lines.append("5. Open a pull request with a clear description.\n")
    lines.append("\n## License\n\n")
    lines.append("- Code and scripts: [MIT](./LICENSE)\n")
    lines.append("- Dataset/content: [CC BY 4.0](./LICENSE-CC-BY)\n")
    lines.append("\n")
    lines.append('<div align="center">\n\n')
    lines.append(
        "Built for North American Computer Science students who want one reliable "
        "place to discover what to learn, "
    )
    lines.append("join, build, attend, and apply for.\n\n")
    lines.append("</div>\n")

    readme = "".join(lines)
    readme_path = ROOT / "README.md"
    with open(readme_path, "w", encoding="utf-8") as f:
        f.write(readme)

    save_json(
        GENERATED_DIR / "README_DATA.json",
        {
            "generated": today,
            "total": total,
            "by_category": {k: len(v) for k, v in by_category.items()},
        },
    )

    log(f"✅ Generated README.md ({total} resources)")

if __name__ == "__main__":
    generate_readme()
