name: Stats

on:
  pull_request:
    branches: [main]

jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-python@v5.6.0
        with:
          python-version: "3.14"
      - run: python scripts/stats.py
