name: Validate Scheduled

on:
  schedule:
    - cron: "0 10 * * 1"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: validate-scheduled-${{ github.ref }}
  cancel-in-progress: false

jobs:
  validate:
    name: Validate
    uses: ./.github/workflows/validate.yml
    permissions:
      contents: read
